export const SELECT_CONTACT='SELECT_CONTACT';
export const ADD='ADD';
export const EDIT='EDIT';
export const DELETE='DELETE';
export const START_CONVERSATION='START_CONVERSATION';
export const END_CONVERSATION='END_CONVERSATION';
export const CREATE_CONVERSATION='CREATE_CONVERSATION';

